// Code generated by "stringer -type=Module"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FundList-1]
	_ = x[FundDetail-2]
	_ = x[FundHoliday-3]
	_ = x[FundDividend-4]
	_ = x[FundHistory-5]
}

const _Module_name = "FundListFundDetailFundHolidayFundDividendFundHistory"

var _Module_index = [...]uint8{0, 8, 18, 29, 41, 52}

func (i Module) String() string {
	i -= 1
	if i < 0 || i >= Module(len(_Module_index)-1) {
		return "Module(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Module_name[_Module_index[i]:_Module_index[i+1]]
}
